### ISSUE TITLE
Autosize setting too much height to my textarea, almost the double

### ISSUE THREAD

**Issue by guillecro** [jackmoore/autosize#213]
Hi there.
So basically I have a textarea of `font-size:50px` and `min-height:82px`.
My problem is that when I trigger `autosize('.textarea')`, it becomes a textarea of almost 2 rows.. I dont know but it is almost the double of what I need. 

How can i keep the textarea of 1 row and then autosize it?
Its because of the `font-size:`? the `min-height:82px`?

Thanks in advance (I can share my CSS if you need).

![help](https://cloud.githubusercontent.com/assets/8771166/6767827/662f7630-d026-11e4-91c4-24ee90f68e0b.png)

**Comment by guillecro** [comment]
Never mind.
I fixed it with `rows=1`
I'll leave this here if anyone wants to comment. Then I'll close this.

**Comment by boynet** [comment]
+1 on this bug.. fixed also by rows=1 but why the default is 2 rows?

**Comment by jackmoore** [comment]
@boynet, Autosize isn't setting the rows to 2 (or to anything), that's just the default value for rows as given by the browser.

**Comment by boynet** [comment]
yeah I just got it :) the rows=1 not helping cuz the textarea is not growing.. I am just debuging the code is there some known way to force it to start with height of 1 row without modifying the core? if not will you accept pr, with initial height to be configured? maybe something like:
````
<textarea data-start-rows=1>
````

**Comment by guillecro** [comment]
Hmm.. Strange, cause for me `rows=1` works and it grows too.
This is how i do it: 
```html
<textarea id="tooltip-titulo" type="text" name="nombre" id="tooltip-nombre" **rows="1"** placeholder="Escriba el nombre del partido"></textarea>
```

And this goes on a `<script></script>`
```javascript
$(document).ready(function(){
        autosize($("textarea[name='nombre']"));
        autosize($("textarea[name='descripcion']"));
    });
```

And this is some CSS for the `<textarea>`
```css
textarea[name=titulo]{
                font-family: "Source Sans Pro",sans-serif;
                font-weight: 700;
                font-style: normal;
               font-size: rem-calc(50);
                text-rendering: optimizelegibility;
                color: #383838;
                border: 0px solid #484848;
                width: 100%;
                min-height: 82px;
                box-shadow: 0px 0px 0px rgba(0, 0, 0, 0);
                text-align: center;
                resize: none;
                &:focus{
                    background-color: #fff4c4;
                }
                margin: 0;
            }
```

Yes, I use min-height there.
