### ISSUE TITLE
Force extra row

### ISSUE THREAD

**Issue by mouse0270** [jackmoore/autosize#224]
Issue #220 states that they are getting `rows + 1` but my issue is that I am not getting the extra row and I would like the padding between the bottom of my text area and the content within it.

**Comment by jackmoore** [comment]
Then use padding-bottom on your textarea?  The rows attribute (or min-height) would be used to set a minimum height.

**Comment by mouse0270** [comment]
I use
``` css
textarea {
	line-height: 1.5;
	min-height: 45px;
	padding-bottom: 15px;
}
```

But it doesn't seem to account for the padding.
