### ISSUE TITLE
rows attribute not working

### ISSUE THREAD

**Issue by knzudgt** [jackmoore/autosize#334]
I am using `gem autosize-rails 1.18.17` with `Rails 5.0.0.1` in a Ubuntu 14.04 LTS machine.
My `textarea` is generated by the following code:

```html+erb
<%= form_for(current_user.comments.build, remote: true) do |f| %>
  <div class="comment-box">
    <%= f.text_area :content, rows: "1" %>
  </div>
  <%= f.submit "Comment", class: "btn btn-primary btn-sm" %>
<% end %>
```

The style associated to `textarea` is:

```css
textarea {
  resize: none;
  border-radius: 5px;
  padding: 4px;
  height: 30px;
  margin-bottom: 2px;
}
```

When I view my code in Firefox 54.0 and Slimjet 13.0.3.0 the textarea height results having rows attribute equal to the default value of 2 instead of 1, as you can see in the picture below.

![screenshot](https://user-images.githubusercontent.com/15718033/27261395-902b12bc-5442-11e7-979d-06801bcfe2f3.png)

My rows attribute was working before installing gem `autosize-rails`
